version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-arch
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: arch
      MONGO_INITDB_ROOT_PASSWORD: arch

  postgres:
    image: postgres
    restart: always
    container_name: postgres-arch
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: postgres
