version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres-b9system
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: postgres
